version: '3.7'

services:
  redis:
    image: redis:5.0.6-alpine
    restart: always

  socket:
    container_name: socket
    build:
      context: ./socket
    restart: always
    depends_on:
      - back
    links:
      - back
    ports:
      - 8001:8001
    volumes:
      - ./socket:/usr/src/app/socket
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  back:
    container_name: back
    restart: always
    depends_on:
      - redis
    links:
      - redis
    build:
      context: ./back
    volumes:
      - ./back:/usr/src/app/back
    ports:
      - 8000:8000

  front:
    container_name: front
    build:
      context: ./front
    restart: always
    depends_on:
      - back
    volumes:
      - ./front:/usr/src/app/front
      - ./front/node_modules:/usr/src/app/front/node_modules
    ports:
      - 3000:3000

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    restart: always
    depends_on:
      - front
      - back
      - socket
    links:
      - front
      - back
      - socket
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443

  kurento:
    build: ./kurento
    restart: always
    environment:
      - KMS_PORT=8888
      - BIND_INTERFACE=eth0
    ports:
      - 8888:8888